version: '3'

services:
  localstack:
    image: 'localstack/localstack'
    restart: always
    environment:
      - SERVICES=dynamodb,sqs,s3
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - ./aws:/docker-entrypoint-initaws.d

  lambda-exemplo:
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      - ENV=local